//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"    // include library files
// segunda prueba. uso de tareas compartiendo variables
#define tamanio_buffer 100
int buffer[tamanio_buffer];
int buffer_copia[tamanio_buffer];
int contador_buffer=0;
int nXAxis;
int nYAxis;
int nZAxis;
tSensors  puerto_acelerometro;
task llenado_buffer()
{
  while (1) {
    wait1Msec(10);
    getAccel(puerto_acelerometro, nXAxis, nYAxis, nZAxis);
    buffer[contador_buffer]=nXAxis;
    contador_buffer++;
    if (contador_buffer==tamanio_buffer) contador_buffer=0;
  }
 }

task main()
{
	//variables

	long T; //tiempo actual
  int  nose;
  int contador2;
  int contador3;

  int contador_buffer_copia;
  while (!findSensor(puerto_acelerometro, "HITECHNC", "Accel.  "))
	{
    wait1Msec(500);
  }
  SensorType[puerto_acelerometro] = sensorI2CHiTechnicAccel; // Configure the sensor
  //borra el contenido del buffer
  for (contador2=0;contador2<tamanio_buffer;contador2++) buffer[contador2]=0;
  T=nSysTime;
  //wait1Msec(20);

  StartTask(llenado_buffer);

  while (1)
  {
      wait1Msec(1000);
      //rellena el buffer copia
      contador_buffer_copia=contador_buffer; //retiene el valor durante el proceso
                                             //porque puede cambiar
      //if (contador_buffer_copia<0) contador_buffer_copia+=tamanio_buffer;
      contador3=0;
      //primera parte, desde el puntero hasta el final
      for (contador2=contador_buffer_copia;contador2<tamanio_buffer;contador2++) {
        buffer_copia[contador3]=buffer[contador2];
        contador3++;
      }
      //segunda parte, desde el principio hasta el puntero-1
      for (contador2=0;contador2<contador_buffer_copia;contador2++) {
        buffer_copia[contador3]=buffer[contador2];
        contador3++;
      }

      T=nSysTime;
      eraseDisplay();
      nxtDisplayString(1, "contador %d   ", contador_buffer);
      nxtDisplayString(2, "%ld  ", T);
      //dibuja la grafica contenida en el buffer
      for (contador2=0;contador2<100;contador2++) {
        nxtDrawLine(contador2,0,contador2,buffer_copia[contador2]/10+20);
      }

  }
}
