//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"    // include library files
// primera prueba. intento de mostrar grficamente la informacion del acelerometro
task main()
{
	//variables
	tSensors  puerto_acelerometro;
	long T; //tiempo actual
  int nXAxis;
  int nYAxis;
  int nZAxis;
  int  nose;
  long contador;

  while (!findSensor(puerto_acelerometro, "HITECHNC", "Accel.  "))
	{
    wait1Msec(500);
  }
  SensorType[puerto_acelerometro] = sensorI2CHiTechnicAccel; // Configure the sensor
  T=nSysTime;
  //wait1Msec(20);
  while (contador<99999)
  {
      getAccel(puerto_acelerometro, nXAxis, nYAxis, nZAxis);
      nose=SensorRaw[puerto_acelerometro];
      T=nSysTime;
      //eraseDisplay();

      //nxtEraseRect(0,

      nxtDisplayString(2, "x %x   ", nXAxis);
      nxtDisplayString(3, "x %x   ", nose);
      //nxtDisplayString(3, "y %d   ", nYAxis);
      //nxtDisplayString(4, "z %d   ", nZAxis);
      nxtDrawLine(contador,0,contador,nXAxis/8);
      nxtEraseLine(contador,nXAxis/8,contador,32);
    	wait1Msec(5);
    	contador++;
    	if (contador>99) {
    	  contador=0;
    	  nxtDisplayString(1, "%ld  ", T);
    	  //eraseDisplay();
    	}
  }
}
